# Generated by Django 3.2 on 2021-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210426_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(),
        ),
    ]
